main/Main/Pages/Assigned.cshtml.cs
using Main.Data;
using Main.Enumerations;
using Main.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Main.Pages;

[Authorize]
public class AssignedModel : PageModel
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly ApplicationRepository _repository;

    public List<QuizRequest> QuizRequests = [];
    public List<Quiz> NotSolvedOpen = [];
    public List<Quiz> NotSolvedPlanned = [];
    public List<Quiz> WaitingForGrade = [];
    public List<Quiz> Graded = [];
    public Dictionary<int, QuizResult> GradedQuizes = [];

    [BindProperty]
    public int RequestId { get; set; }

    public AssignedModel(ApplicationRepository repository, UserManager<ApplicationUser> userManager)
    {
        _userManager = userManager;
        _repository = repository;
    }

    public async Task<IActionResult> OnGetAsync()
    {
        var appUser = await _userManager.GetUserAsync(User);
        if (appUser == null)
        {
            return Forbid();
        }

        var user = await _repository.GetAsync<ApplicationUser>(
            u => u.Id == appUser.Id,
            u => u
                .Include(u => u.QuizResults)
                .Include(u => u.ParticipatedQuizes)
                    .ThenInclude(q => q.Exercises)
                        .ThenInclude(e => e.ExerciseSolutions.Where(es => es.UserId == appUser.Id))
                .Include(u => u.ParticipatedQuizes)
                    .ThenInclude(q => q.Creator)
                .Include(u => u.QuizRequests)
                    .ThenInclude(qr => qr.Quiz)
                        .ThenInclude(q => q.Creator)
        );

        if (user == null)
        {
            return RedirectToPage("/Error");
        };

        QuizRequests = user.QuizRequests.ToList();

        GradedQuizes = user.QuizResults
            .Where(qr => qr.Grade != null)
            .ToDictionary(qr => qr.QuizId);

        foreach (var quiz in user.ParticipatedQuizes.Reverse())
        {
            bool isSolved = quiz.Exercises.Any(e => e.ExerciseSolutions.Any(es => es.UserId == appUser.Id));

            if (isSolved || quiz.State == QuizState.Closed)
            {
                if (GradedQuizes.ContainsKey(quiz.Id))
                {
                    Graded.Add(quiz);
                }
                else
                {
                    WaitingForGrade.Add(quiz);
                }
            }
            else
            {
                if (quiz.State == QuizState.Open)
                    NotSolvedOpen.Add(quiz);
                else if (quiz.State == QuizState.NotStarted)
                    NotSolvedPlanned.Add(quiz);
            }
        }
        return Page();
    }

    public async Task<IActionResult> OnPostDeclineRequest()
    {
        var currentUser = await _userManager.GetUserAsync(User);
        if (currentUser == null)
        {
            return Forbid();
        }

        var quizRequest = await _repository.GetAsync<QuizRequest>(qr => qr.Id == RequestId);
        if (quizRequest == null)
        {
            return Forbid();
        }

        _repository.Delete(quizRequest);
        await _repository.SaveChangesAsync();

        return RedirectToPage();
    }
}

main/Main/Pages/Create.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Main.Data;
using Main.Enumerations;
using Main.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Main.Pages
{
    public class CreateModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationRepository _repository;

        [BindProperty]
        [Display(Name = "Quiz Name")]
        [Required(ErrorMessage = "Quiz name is required.")]
        public string QuizName { get; set; } = null!;
        [BindProperty]
        [Display(Name = "Open Date")]
        [Required(ErrorMessage = "Open date is required.")]
        public DateTime? OpenDate { get; set; } = null;
        [BindProperty]
        [Display(Name = "Close Date")]
        [Required(ErrorMessage = "Close date is required.")]
        public DateTime? CloseDate { get; set; } = null;
        [BindProperty]
        public List<string> Questions { get; set; } = null!;
        [BindProperty]
        public int? EditedQuizId { get; set; } = null;

        [BindProperty]
        public string? Code { get; set; }

        public bool BrowseOnly { get; set; } = false;

        public CreateModel(ApplicationRepository repository, UserManager<ApplicationUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            //create new quiz
            if (id == null)
            {
                return Page();
            }

            var appUser = await _userManager.GetUserAsync(User);
            var quiz = await _repository.GetAsync<Quiz>(
                filter: q => q.Id == id,
                modifier: q => q.Include(r => r.Excersises)
            );

            if (quiz == null || appUser == null || appUser.Id != quiz.CreatorId)
            {
                return Forbid();
            }

            BrowseOnly = quiz.IsCreated;

            EditedQuizId = quiz.Id;
            QuizName = quiz.Name;
            CloseDate = quiz.CloseDate;
            OpenDate = quiz.OpenDate;
            Code = quiz.Code;
            Questions = quiz.Excersises.Select(e => e.Question).ToList();

            return Page();
        }

        public async Task<IActionResult> OnPostSave()
        {
            
            var currentUser = (await _userManager.GetUserAsync(User))!;
            if (currentUser == null)
                return RedirectToPage("Error");

            if (EditedQuizId == null)
            {
                var quiz = new Quiz()
                {
                    Name = QuizName,
                    OpenDate = (DateTime)OpenDate!,
                    CloseDate = (DateTime)CloseDate!,
                    CreatorId = currentUser.Id,

                    //TODO: TESTING PURPOSES ONLY, REMOVE THIS
                    Participants = new List<ApplicationUser>() { currentUser }
                };
                
                _repository.Add(quiz);
                
                await _repository.SaveChangesAsync();

                foreach (string question in Questions!)
                {
                    _repository.Add(new Excersise()
                    {
                        Question = question,
                        QuizId = quiz.Id,
                    });
                }
            }
            else
            {
                var editedQuiz = await _repository.GetAsync<Quiz>(
                    filter: q => q.Id == EditedQuizId,
                    modifier: q => q.Include(r => r.Excersises)
                );

                if (editedQuiz == null)
                    return RedirectToPage("Error");

                editedQuiz.Name = QuizName;
                editedQuiz.OpenDate = (DateTime)OpenDate!;
                editedQuiz.CloseDate = (DateTime)CloseDate!;
                
                _repository.Update(editedQuiz);
                
                await _repository.SaveChangesAsync();

                foreach (var question in editedQuiz.Excersises)
                {
                    _repository.Delete(question);
                }

                foreach (var question in Questions)
                {
                    _repository.Add(new Excersise()
                    {
                        Question = question,
                        QuizId = editedQuiz.Id,
                    });
                }
            }

            await _repository.SaveChangesAsync();

            return RedirectToPage("listcreate");
        }

        public async Task<IActionResult> OnPostSubmit()
        {           
    
            if (CloseDate <= OpenDate)
            {
                ModelState.AddModelError(nameof(CloseDate), "Close date can't be older than open date.");;
            }
            if (CloseDate <= DateTime.Now)
            {
                ModelState.AddModelError(nameof(CloseDate), "Close date can't be older than current date."); ;
            }

            if (Questions.Count == 0)
            {
                ModelState.AddModelError(nameof(Questions), "At least one excersise is required.");
            }
            else if (Questions.Any(q => q == ""))
            {
                ModelState.AddModelError(nameof(Questions), "No excersise can be empty.");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }
        
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
                return RedirectToPage("Error");

            if (EditedQuizId == null)
            {
                var quiz = new Quiz()
                {
                    Name = QuizName,
                    OpenDate = (DateTime)OpenDate!,
                    CloseDate = (DateTime)CloseDate!,
                    CreatorId = currentUser.Id,
                    IsCreated = true,

                    //TODO: TESTING PURPOSES ONLY, REMOVE THIS
                    Participants = new List<ApplicationUser>() { currentUser },
                };
                
                _repository.Add(quiz);
                
                await _repository.SaveChangesAsync();

                foreach (string question in Questions!)
                {
                    _repository.Add(new Excersise()
                    {
                        Question = question,
                        QuizId = quiz.Id,
                    });
                }
            }
            else
            {
                var editedQuiz = await _repository.GetAsync<Quiz>(
                    filter: q => q.Id == EditedQuizId,
                    modifier: q => q.Include(r => r.Excersises)
                );

                if (editedQuiz == null)
                    return RedirectToPage("Error");

                editedQuiz.Name = QuizName;
                editedQuiz.OpenDate = (DateTime)OpenDate!;
                editedQuiz.CloseDate = (DateTime)CloseDate!;
                editedQuiz.IsCreated = true;
                
                _repository.Update(editedQuiz);
                
                await _repository.SaveChangesAsync();

                foreach (var question in editedQuiz.Excersises)
                {
                    _repository.Delete(question);
                }

                foreach (var question in Questions)
                {
                    _repository.Add(new Excersise()
                    {
                        Question = question,
                        QuizId = editedQuiz.Id,
                    });
                }
            }

            await _repository.SaveChangesAsync();

            return RedirectToPage("ListCreate");
        }
    }
}

main/Main/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Main.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        private const string DEFAULT_ERROR_MESSAGE = "Podczas przetwarzania twojego zapytania wystąpił błąd. Strona do której się odwołujesz nie istnieje lub nie masz do niej dostępu.";

        public string ErrorMessage { get; set; } = null!;

        public string? RequestId { get; set; }

        public void OnGet(string? errorMessage)
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            ErrorMessage = errorMessage ?? DEFAULT_ERROR_MESSAGE;
        }
    }

}

main/Main/Pages/GroupDetails.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Humanizer;
using Main.Data;
using Main.Enumerations;
using Main.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Main.Pages
{
    [Authorize]
    public class GroupDetailsModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationRepository _repository;

        [BindProperty]
        [Display(Name = "Group Name")]
        [Required(ErrorMessage = "Group name is required.")]
        public string GroupName { get; set; } = null!;
        
        
        [BindProperty]
        public List<string> Emails { get; set; } = [];
        [BindProperty]
        public int? GroupId { get; set; } = null;
        [BindProperty]
        public string? UserId { get; set; } = null;
        [BindProperty]
        public bool ForTeachers { get; set; }

        public List<ApplicationUser> Students { get; set; } = [];

        public List<ApplicationUser> Teachers { get; set; } = [];

        public List<GroupRequest> Requests { get; set; } = [];

        public int Id { get; set; } = 0;

        public GroupDetailsModel(ApplicationRepository repository, UserManager<ApplicationUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(int? id)
        {

            var appUser = await _userManager.GetUserAsync(User);
            var group = await _repository.GetAsync<UsersGroup>(
                filter: q => q.Id == id,
                modifier: q => q
                    .Include(g => g.Requests)
                        .ThenInclude(r => r.User)
                    .Include(g => g.Students)
                    .Include(g => g.Teachers)
            );

            if (group == null || appUser == null || !group.Teachers.Any(t => t.Id == appUser.Id))
            {
                return Forbid();
            }

            Teachers = group.Teachers.ToList();

            Students = group.Students.ToList();

            Requests = group.Requests.ToList();

            GroupId = id;

            return Page();
        }

        public async Task<IActionResult> OnPostSendRequests()
        {            
            var currentUser = (await _userManager.GetUserAsync(User))!;
            if (currentUser == null)
            {
                return RedirectToPage("Error");
            }

            var requestUsers = new List<ApplicationUser>();

            var nonExistingMails = new List<string>();

            foreach(var email in Emails)
            {
                var user = await _repository.GetAsync<ApplicationUser>(u => u.Email == email);

                if (user == null)
                {
                    nonExistingMails.Add(email);
                }
                else
                {
                    requestUsers.Add(user);
                }
            }

            // if (nonExistingMails.Any())
            // {
            //     if (nonExistingMails.Count == 1)
            //     {
            //         ModelState.AddModelError(nameof(Emails), $"Nie istnieje użytkownik z mail-em: {nonExistingMails.First()}");
            //     }
            //     else
            //     {
            //         ModelState.AddModelError(nameof(Emails), $"Nie istnieją użytkownicy z mail-ami: {nonExistingMails.Humanize()}");
            //     }
            // }
            
            var group = await _repository.GetAsync<UsersGroup>(
                filter: q => q.Id == GroupId,
                modifier: q => q
                    .Include(g => g.Requests)
                    .Include(g => g.Teachers)
            );

            if (group == null)
            {
                return RedirectToPage("Error");
            }

            foreach (var user in requestUsers)
            {
                _repository.Add(new GroupRequest()
                {
                    Group = group,
                    User = user,
                    ForTeacher = ForTeachers,
                    ExpirationDate = DateTime.Now.AddDays(7),
                });
            }

            await _repository.SaveChangesAsync();

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveFromGroup()
        {
            var currentUser = (await _userManager.GetUserAsync(User))!;
            if (currentUser == null)
            {
                return RedirectToPage("Error");
            }

            var userToRemove = await _repository.GetAsync<ApplicationUser>(
                u => u.Id == UserId,
                q => q
                    .Include(u => u.TeacherInGroups)
                    .Include(u => u.StudentInGroups)
            );

            if (userToRemove == null)
            {
                return RedirectToPage("Error");
            }

            var group = await _repository.GetAsync<UsersGroup>(
                g => g.Id == GroupId
            );

            if (group == null)
            {
                return RedirectToPage("Error");
            }

            if (ForTeachers)
            {
                group.Teachers.Remove(userToRemove);
            }
            else
            {
                group.Students.Remove(userToRemove);
            }

            _repository.Update(group);

            await _repository.SaveChangesAsync();

            return RedirectToPage();
        }
    }
}

main/Main/Pages/Create.cshtml
@page
@model Main.Pages.CreateModel

<head>
    <link rel="stylesheet" href="~/css/create-style.css" />
</head>

<form method="post" class="h-100 w-100">
    <div class="h-100 w-100 d-flex flex-column">
        <div class="flex-grow-1 d-flex overflow-auto">
            <div class="left-panel">
                <div class="mb-3">
                    <label asp-for="QuizName" class="form-label"></label>
                    <input asp-for="QuizName" class="form-control" readonly="@Model.BrowseOnly">
                    <span asp-validation-for="QuizName" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="OpenDate" class="form-label"></label>
                    <input asp-for="OpenDate" class="form-control" readonly="@Model.BrowseOnly">
                    <span asp-validation-for="OpenDate" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="CloseDate" class="form-label"></label>
                    <input asp-for="CloseDate" class="form-control" readonly="@Model.BrowseOnly">
                    <span asp-validation-for="CloseDate" class="text-danger"></span>
                </div>
            </div>

            <div class="vr mx-3"></div>

            <div class="flex-grow-1 d-flex flex-column overflow-auto">
                <span asp-validation-for="Questions" id="questions-validation-error" class="text-danger mb-1"></span>

                <div id="excersise-container" class="d-flex flex-column">
                    @* EXCERSISES ARE FILLED WITH JS SCRIPT *@
                </div>

                @if (!Model.BrowseOnly)
                {
                    <div class="task task-add d-flex justify-content-center align-items-center" onclick="addExcersise()">
                        <span class="plus">+</span>
                        <span>Dodaj nowe zadanie</span>
                    </div>
                }
            </div>
        </div>

        <hr class="hr">

        <input type="hidden" asp-for="EditedQuizId" value="@Model.EditedQuizId" />
        <div class="bottom-bar d-flex align-items-center">
            <a asp-page="Index" class="btn btn-danger btn-std-width">Powrót</a>
            @if (!Model.BrowseOnly)
            {
                <button type="submit" asp-page-handler="Submit" class="btn btn-primary btn-std-width ms-auto">Opublikuj</button>
                <button type="submit" asp-page-handler="Save" class="btn btn-primary btn-std-width ms-auto">@(Model.EditedQuizId == null ? "Utwórz" : "Zapisz")</button>
            }
            else
            {
                <button type="button" class="btn btn-primary btn-std-width ms-auto">@(Model.Code == null ? "Quiz zakończony" : "KOD: " + Model.Code)</button>
                @if (Model.Code != null)
                {
                    <button type="button" class="btn btn-primary btn-std-width ms-auto" onclick="navigator.clipboard.writeText('harmony.io/solve?id=@Model.Code')">Skopiuj link quizu do schowka</button>
                }
            }
        </div>
    </div>
</form>


<script>
    let excersises = @Html.Raw(Json.Serialize(Model.Questions?.Select(q => q ?? "").ToList() ?? new List<string>()));

    function addExcersise() {
        excersises.push("");
        renderExcersises();

        document.getElementById('questions-validation-error').innerText = '';
    }

    function updateExcersise(index, value) {
        excersises[index] = value;

        document.getElementById('questions-validation-error').innerText = '';
    }

    function removeExcersise(index) {
        excersises.splice(index, 1);
        renderExcersises();
    }

    function renderExcersises() {
        const excersiseContainer = document.getElementById('excersise-container');
        excersiseContainer.innerHTML = '';

        excersises.forEach((excersise, index) => {
            // Excercises should be loaded here, so creators also

            excersiseContainer.innerHTML += `
                <div class="task task-creator p-0 overflow-hidden">
                    <div class="d-flex h-100 align-items-center bg-secondary">
                        <div class="task-number text-white">${index + 1}</div>
                        <div class="vr"></div>
                    </div>
                    <div class="task-content w-100 p-3">
                        <span class="mb-1">Kreator funkcji</span> @*Tutaj trzeba dodać kreatory*@
                        <input type="text" name="Questions[${index}]" class="form-control task-input" value="${excersise}" oninput="updateExcersise(${index}, this.value)" @(Model.BrowseOnly ? "readonly" : "")>
                    </div>
                    @if (!Model.BrowseOnly)
                    {
                        <div class="d-flex h-100 align-items-center">
                            <div class="vr"></div>
                            <button class="delete-btn" onclick="removeExcersise(${index})">🗑️</button>
                        </div>
                    }
                </div>`;
        });
    }

    renderExcersises();
</script>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

main/Main/Pages/GroupDetails.cshtml
@page
@model Main.Pages.GroupDetailsModel

<head>
    <link rel="stylesheet" href="~/css/creator-style.css" />
</head>

<div class="h-100 w-100 d-flex flex-row overflow-auto">
    <div class="w-50 flex-grow-1 overflow-auto d-flex flex-column pe-3">
        <div class="fw-bold fs-4 mb-3">Nauczyciele</div>
        @foreach (var user in Model.Teachers)
        {
            <div class="quiz p-0 flex-shrink-0 d-flex flex-row overflow-hidden p-3">
                <div class="flex-grow-1 d-flex flex-column">
                    <div class="fw-bold fs-5 mb-3">@user.FullName</div>

                    <form method="post" class="ms-auto mt-auto">
                        <input type="hidden" asp-for="UserId" value="@user.Id" />
                        <input type="hidden" asp-for="GroupId" value="@Model.GroupId"/>
                        <input type="hidden" asp-for="ForTeachers" value="@true" />
                        <button type="submit" asp-page-handler="QuitGroup" class="btn btn-danger">Usuń z grupy</button>
                    </form>
                </div>
            </div>
        }
        <div class="no-style" data-bs-toggle="modal" data-bs-target="#teacherModal">
            <div class="quiz quiz-add d-flex justify-content-center align-items-center">
                <span class="plus me-1">+</span>
                <span>Dodaj nauczycieli</span>
            </div>
        </div>

        <div class="fw-bold fs-4 mb-3">Studenci</div>
        @foreach (var user in Model.Students)
        {
            <div class="quiz p-0 flex-shrink-0 d-flex flex-row overflow-hidden p-3">
                <div class="flex-grow-1 d-flex flex-column">
                    <div class="fw-bold fs-5 mb-3">@user.FullName</div>

                    <form method="post" class="ms-auto mt-auto">
                        <input type="hidden" asp-for="UserId" value="@user.Id" />                            
                        <input type="hidden" asp-for="ForTeachers" value="@false" />
                        <button type="submit" asp-page-handler="QuitGroup" class="btn btn-danger">Usuń z grupy</button>
                    </form>
                </div>
            </div>
            
        
        }    
        <div class="no-style" data-bs-toggle="modal" data-bs-target="#studentModal">
            <div class="quiz quiz-add d-flex justify-content-center align-items-center">
                <span class="plus me-1">+</span>
                <span>Dodaj uczniów</span>
            </div>
        </div>
    </div> 

    <div class="vr"></div>

    <div class="w-50 flex-grow-1 overflow-auto d-flex flex-column ps-3">
        <div class="fw-bold fs-4 mb-3">Nauczyciele</div>
        @foreach (var request in Model.Requests)
        {
            <div class="quiz p-0 flex-shrink-0 d-flex flex-row overflow-hidden p-3">
                <div class="flex-grow-1 d-flex flex-column">
                    <div class="fw-bold fs-5 mb-3">@request.User.Email</div>
                    <div class="d-flex flex-row align-items-center">
                        <i class="fas fa-music icon-sm me-2"></i>
                        <span class="fw-bold me-1">Wygasa:</span>
                        <span>@request.ExpirationDate</span>
                    </div>
                </div>

                <div class="d-flex flex-column h-100">
                    <form method="post" class="ms-auto mt-auto">
                        <input type="hidden" asp-for="Id" value="@request.Id" />
                        <button type="submit" asp-page-handler="RmRequest" class="btn btn-outline-primary">Usuń</button>
                    </form>
                </div>
            </div>
        }

        

    </div>
</div>



@foreach(var forTeachers in new[] {true, false})
{
    var x = forTeachers ? "Teacher" : "Student";

    <!-- Modal -->
    <div class="modal fade" id="@(forTeachers ? "teacherModal" : "studentModal")" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <form method="post" class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Dodaj @(forTeachers ? "nauczycieli" : "uczniów")</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
                <div class="d-flex flex-column">
                    <div class="flex-grow-1 d-flex overflow-auto">
                        <div class="flex-grow-1 d-flex flex-column overflow-auto">
                            <div class="mb-3">
                                <input type="hidden" asp-for="GroupId" value="@Model.GroupId" />                            
                                <input type="hidden" asp-for="ForTeachers" value="@forTeachers" />

                                <span asp-validation-for="Emails" id="emails@(x)-validation-error" class="text-danger mb-1"></span>

                                <div id="email@(x)-container" class="d-flex flex-column">
                                    @* MAIL INPUTS ADDED WITH JS *@
                                </div>
                                <div class="task task-add d-flex justify-content-center align-items-center" onclick="addEmail@(x)()">
                                    <span class="plus">+</span>
                                    <span>Dodaj email</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        <div class="modal-footer">
            <button type="submit" asp-page-handler="SendRequests" class="btn btn-primary btn-std-width ms-auto">Zaproś do grupy</button>
        </div>
        </form>
    </div>
    </div>

    
    <script>
        let emails@(x) = [];
        function addEmail@(x)() {
            emails@(x).push("");
            renderEmails@(x)();
            document.getElementById('emails@(x)-validation-error').innerText = '';
        }
        function updateEmail@(x)(index, value) {
            emails@(x)[index] = value;
            document.getElementById('emails@(x)-validation-error').innerText = '';
        }
        function removeEmail@(x)(index) {
            emails@(x).splice(index, 1);
            renderEmails@(x)();
        }
        function renderEmails@(x)() {
            const emailContainer = document.getElementById('email@(x)-container');
            emailContainer.innerHTML = '';
            emails@(x).forEach((email, index) => {
                emailContainer.innerHTML += `
                    <div class="task task-creator p-0 overflow-hidden">
                        <div class="d-flex h-100 align-items-center bg-secondary">
                            <div class="task-number text-white">${index + 1}</div>
                            <div class="vr"></div>
                        </div>
                        <div class="task-content w-100 p-3">
                            <input type="text" name="Emails@(x)[${index}]" class="form-control task-input" value="${email}" oninput="updateEmail@(x)(${index}, this.value)">
                        </div>
                        <div class="d-flex h-100 align-items-center">
                            <div class="vr"></div>
                            <button class="delete-btn" onclick="removeEmail@(x)(${index})">🗑️</button>
                        </div>
                    </div>`;
            });
        }
        renderEmails@(x)();
    </script>
}

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}